config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'tasks#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    
    resources :users, only: [:create]
    resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  
  validates :status, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 255 }
                                      
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 25 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, presence: true,length: { minimum: 6 }  
  
  has_many :tasks 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
     
    include SessionsHelper
     
    private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      #この場合はモデルがない為error/messagesのパーシャル設定不可
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    #before_action :set_task, only: [:show, :destroy] #before_actionのcorrect_userで定義済み
    before_action :require_user_logged_in
    before_action :correct_user, only: [:edit, :update, :show,:destroy]

    def index
        #@task = current_user.tasks.build　#投稿の作成だから今回は不要
        @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(10)
        #@tasks = Task.all.page(params[:page]).per(10)
    end
    
    def show
        #set_task
        #@tasks = Task.find(params[:id]) #before_action使用
    end
    
    def new
        #@tasks = Task.new
        @task = current_user.tasks.new #一対多反映機能
    end
    
    def create
        #@tasks = Task.new(task_params)
        @task = current_user.tasks.new(task_params) #一対多反映機能
        
        if @task.save
            flash[:success] = 'タスクが正常に入力されました。'
            redirect_to @task
        else
            flash.now[:danger] = 'タスクが正常に入力されませんでした'
            render :new
        end
        
    end
    
    
    def edit
        #set_task
        @task = Task.find(params[:id])
    end
    
    def update
        #set_task
        @task = Task.find(params[:id])
        
        if @task.update(task_params)
            flash[:success] = 'タスクは正常に更新されました'
            redirect_to @task
        else flash.now[:danger] = 'タスクは更新されませんでした。'
            render :edit
        end
    end
    
    def destroy
        #set_task
        #@tasks = Task.find(params[:id]) before_action利用
        @tasks.destroy
        
        flash[:success] = 'タスクは正常に削除されました。'
        redirect_to tasks_url
    end

  private 
  
    #def set_task #correct_userメソッドで定義済みの為不要
        #@tasks = Task.find(params[:id]) 
    #end  
    
    def task_params
        params.require(:task).permit(:content, :status)
    end
    
    def correct_user
        @tasks = current_user.tasks.find_by(id: params[:id])
     unless @tasks
        redirect_to root_url
     end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :require_user_logged_in, only: [:show] ユーザー詳細画面がないので必要ない
  

  #def show ユーザー詳細画面がないので必要ない
    #@tasks = @user.tasks.order(id: :desc).page(params[:page]).per(10)
  #end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end  
  
    private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0"> 
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div><%= message %></div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href="/">タスク管理表</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
      <%= render 'layouts/navbar' %>
      
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-6">

<%= form_with(model: @task, local: true) do |f| %>


<div class="form-group">
  <%= f.label :ステータス %>
  <%= f.text_field :status, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :タスク内容 %>
  <%= f.text_field :content, class: 'form-control' %>
</div>

  <%= f.submit '入力', class: 'btn btn-primary' %>

<% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= form_with(model: @task, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

<%= render 'form', task: @task %>

<% end %>

<p><%= link_to '一覧に戻る', tasks_path %>
<%= link_to 'NEWタスク作成', new_task_path %></p>

app/views/tasks/index.html.erb
<p>ログインユーザ: <%= current_user.name %>さん</p>

<h1>タスク一覧</h1>
<h2><%= link_to 'タスク新規作成', new_task_path, class:"btn btn-primary" %></h2>



<% if @tasks.any? %>
<table class='table table-striped'>
    <thead>
        <tr>
       <th>ステータス</tt>
       <th>タスク内容</th>
       <th>詳細確認</th>
       <th>編集する</th>
       <th>削除する</th>
        </tr>
    </thead>
    <tbody>
    <% @tasks.each do |task| %>
       <tr>
       <td><%= task.status %></td>
       <td><%= task.content %></td>
       <td><%= link_to '詳細', task_path(task) %></td>
       <td><%= link_to '編集', edit_task_path(task) %></td>
       <td><%= link_to '削除', task_path(task), method: :delete, data: { confirm: '本当に削除してよろしいですか'} %></td>
       <tr>
    <% end %>
    </tbody>
</table>


<% end %>

<div>
    <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>タスク作成ページ</h1>

<%= form_with(model: @task, local: true) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>

<%= render 'form', task: @task %>

<% end %>

<%= link_to 'タスク一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<h2><%= link_to '一覧に戻る', tasks_path, class:"btn btn-primary" %>
<%= link_to 'このタスクを編集する', edit_task_path(@tasks), class: 'btn btn-secondary' %></h2>

<table class="table table-bordered">
    <tr>
        <th>ステータス</th>
        <td><%= @tasks.status %></td>
    </tr>
    <tr>
        <th>タスク内容</th>
        <td><%= @tasks. content %></td>
    </tr>
</table>


<%= link_to 'このタスクを削除する', @tasks, method: :delete, data: { confirm: '本当に削除してよろしいですか'}, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>